### ISSUE TITLE
Sometime long username cannot be linkable or mentioned 

### ISSUE THREAD

**Issue by ppdcom** [Wolfsblvt/mentions#30]
Some time if trying to mention long username they just display as simple text and not as clickable link as other username as mentioned fine. Please check both below 

![snag-0002](https://cloud.githubusercontent.com/assets/1098177/7294012/2a3d35a2-e9c3-11e4-8267-c47cecb55e41.jpg)
![snag-0001](https://cloud.githubusercontent.com/assets/1098177/7294011/2990eedc-e9c3-11e4-81e0-5563e0cd33bc.jpg)

**Comment by Wolfsblvt** [comment]
@Mentions are searched to a maximum length that is specified in the ACP for usernames. Can you confirm that this username is shorter than the number specified?

**Comment by ppdcom** [comment]
Yes Its works now. Username was longer than the username limit that I have changed recently. Thanks for help.

**Comment by Wolfsblvt** [comment]
Okay, thank you for that feedback (:
